version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  deploy-prod:
    docker:
      - image: circleci/node
      - image: circleci/postgres
    steps:
      - checkout
      - run: echo $DROPLET_USER
      - add_ssh_keys
      - run: ssh-keyscan $DROPLET_IP >> ~/.ssh/known_hosts
      - run: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP './deploy_project.sh'
  build-and-test-client:
    executor:
      name: node/default
    steps:
      - checkout
      - run: cd ./client && npm install && npm test
  build-and-test-server:
    docker:
      - image: circleci/node
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: justfortesting
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - run: 
          name: Connect to db
          command: |
            dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: cd ./server && npm install
      - run: 
          name: Seed db & test
          command: |
            cd ./server
            npm run migrate:reset
            npm run test
workflows:
    deploy:
      jobs:
        - build-and-test-client
        - build-and-test-server
        - deploy-prod:
            requires:
              - build-and-test-client
              - build-and-test-server