version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  deploy-prod:
    docker:
      - image: circleci/node
      - image: circleci/postgres
    steps:
      - checkout
      - run: echo $DROPLET_USER
      - add_ssh_keys
      - run: ssh-keyscan 167.172.202.218 >> ~/.ssh/known_hosts
      - run: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@167.172.202.218 './deploy_project.sh'
  build-and-test-client:
    executor:
      name: node/default
    steps:
      - checkout
      - run: cd ./client && npm install && npm test
  build-and-test-server:
    executor:
      name: node/default
    steps:
      - checkout
      - run: apt-get install postgresql-client
      - run: 
          - name: npm install
          - command: |
          cd ./server && npm install
          createdb test_db -U postgres
          sequelize db:seed:all
          npm run migrate:test
workflows:
    build-and-test:
      jobs:
        - build-and-test-client
        - build-and-test-server
    deploy:
      jobs:
        - deploy-prod